/*
Given a string, we have to find out all its subsequences of it. A string is a subsequence of a given String, that is generated by deleteing some character of a given string without changing its order.

Input: abc
Output: a,b,c,ab,bc,ac,abc.
*/

#include <iostream>
#include <bits/stdc++.h>
using namespace std;

void f(string &str, int i, string result, vector<string> &li)
{
    // base case
    if (i == str.length())
    {
        li.push_back(result);
        return;
    }
    // recursive case.
    f(str, i + 1, result + str[i], li);
    f(str, i + 1, result, li);
}

int main()
{
    vector<string> result;
    string str = "abc";
    f(str,0,"",result);
    for(int i=0;i<result.size();i++)
    {
        cout<<result[i]<<" ";
    }
    return 0;
}